### ISSUE TITLE
Create a page which propose you a localized Nightly when possible.

### ISSUE THREAD

**Issue by MatonAnthony** [pascalchevrel/nightly-reboot#3]
I think, it could be interesting to have a page which would propose to download a localized version of Nightly when possible.

**Comment by sylveon** [comment]
Something like [that](https://www.mozilla.org/en-US/firefox/all/) or an automatic selector?

For now, they can be accessed from https://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central-l10n/

**Comment by MatonAnthony** [comment]
I don't know, I would be happy with that : https://www.mozilla.org/en-US/firefox/all/ but for Nightly.
An automated selector could also be awesome.

@pascalchevrel ?

**Comment by pascalchevrel** [comment]
I would be happy with https://www.mozilla.org/en-US/firefox/nightly/all/, I reached out to the webdev team at mozilla.org but they can't put resources on it, so I guess that if we want it, we could do it if we provide the patch to add the page.

**Comment by MatonAnthony** [comment]
How hard would it be ? I suppose it's based on bedrock ?

**Comment by pascalchevrel** [comment]
yes it's a bedrock page, probably not too hard as there are already similar pages for the release channel but I expect the download link generation to be it's own logic for nightly (some python + unit tests) because the download links helpers most likely only deal with channels that get releases every 6 weeks, not with Nightly which is built every day.

**Comment by MatonAnthony** [comment]
We don't need / want a page for Fennec Nightly in the immediate ?

**Comment by sylveon** [comment]
Generally, they use the same page, who also detects the OS.

Also, it may be a good idea to add Firefox Nightly [here](https://www.mozilla.org/en-US/firefox/channel/)

**Comment by pascalchevrel** [comment]
Update:
We now have https://www.mozilla.org/en-US/firefox/nightly/all/
Kohei is working on the same page for Android https://bugzilla.mozilla.org/show_bug.cgi?id=1301650

Nightly should get a spot on the future pre-release channels page which would replace the /channel page https://bugzilla.mozilla.org/show_bug.cgi?id=1299947

**Comment by sylveon** [comment]
There is no link for the localised version in https://nightly.mozilla.org/

**Comment by pascalchevrel** [comment]
We may add a link on nightly.mozilla.org but the goal is to redirect that site to a real Nightly download section on www.mozilla.org, if it takes a lot of time to do so, we will probably put a link.

**Comment by pascalchevrel** [comment]
Provide a link to localized Desktop Nightlies on nightly.mozilla.org https://bugzilla.mozilla.org/show_bug.cgi?id=1302728

**Comment by pascalchevrel** [comment]
done

**Comment by sylveon** [comment]
[Link for the lazy](https://www.mozilla.org/en-US/firefox/nightly/all/)

**Comment by pascalchevrel** [comment]
nightly.mozilla.org now displays a localized download page
