### ISSUE TITLE
Add the fox on the Firefox Nightly logo

### ISSUE THREAD

**Issue by sylveon** [pascalchevrel/nightly-reboot#4]
I know this might be a bit asking to the branding team, but why not adding the fox on the Nightly logo?

Firefox Nightly is the only browser not having the fox on it's logo since Aurora changed for Developer Edition.

Many times, people see my browser's logo and asks me what is the browser that I use. I have to explain to them what exactly is Firefox Nightly. Adding a fox on it will help recognize it is still Firefox.

**Comment by pascalchevrel** [comment]
That's indeed a branding issue, I expect that the marketing folks will not want to dillute the Firefox brand by adding a logo there. On the other hand, that gives the opportunity to build our own visual communication without depending on the Firefox logo and its use restriction.

I think this is a decision that could be revised if we get a lot more Nightly users actually. I could imagine for example a Nightly logo with a fireframed fox on it, no colors.

**Comment by sylveon** [comment]
Something like that?
![nightly](https://cloud.githubusercontent.com/assets/6440374/15903276/f3fea7a4-2d79-11e6-8c57-a679b6a5505e.png)

**Comment by MichaelKohler** [comment]
I kind of like it, but as has been said before, this might be a branding topic.

Looking at the logo I discovered that this might be too similar to the dev edition logo though, and I just looked at the logo and my dock:

![screen shot 2016-06-23 at 00 17 26](https://cloud.githubusercontent.com/assets/330324/16285707/047dfc7e-38d8-11e6-8195-d852d62f9ddc.png)

**Comment by pascalchevrel** [comment]
It's very unlikely that the Firefox team will want the fox on the logo for Nightly for brand recognition issues to be honest

**Comment by sylveon** [comment]
I gave it a try again, and we could have a polar fox instead of red fox:
![firefox-nightly_logo-only_rgb](https://cloud.githubusercontent.com/assets/6440374/21705578/d04311ea-d38e-11e6-934b-58a46b8e7bb9.png)

IMO it would look much better if we would invert the white and blue, here's my attempt at doing it:
![firefox-nightly_logo-only_rgb-inverted](https://cloud.githubusercontent.com/assets/6440374/21705599/f16cb9a2-d38e-11e6-9a14-d7de75dc20a3.png)

**Comment by sylveon** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1387254
